[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nachet_datastore"
version = "1.0.0"
authors = [
  { name="Francois Werbrouck", email="francois.werbrouck@inspection.gc.ca" },
  { name="Sylvanie You", email="Sylvanie.You@inspection.gc.ca"}
]
description = "Data management python layer"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dynamic = ["dependencies"]


license = { file = "LICENSE" }  

keywords = ["Nachet","ailab"]

[tool.setuptools.packages.find]
where = ["."]
include = ["nachet*", "datastore*"]


[tool.setuptools.dynamic]
dependencies = {file = ["./datastore/requirements.txt"]}

# https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
# [tool.setuptools.packages.find]
# where = ["ailab"]

[project.urls]
"Homepage" = "https://github.com/ai-cfia/ailab-datastore"
"Bug Tracker" = "https://github.com/ai-cfia/ailab-datastore/issues"
Repository = "https://github.com/ai-cfia/ailab-datastore"  
