---
    name: ai-cfia workflows
    
    on:
      pull_request:
        types:
          - opened
          - closed
          - synchronize
    
    
    jobs:
      python-lint:
        name: workflow-lint-test-python
        uses: ai-cfia/github-workflows/.github/workflows/workflow-lint-test-python.yml@main
        secrets: inherit
      mkd-check:
        name: workflow-markdown-check
        uses: ai-cfia/github-workflows/.github/workflows/workflow-markdown-check.yml@main
        secrets: inherit
      repo-validation:
        name: workflow-repo-standards-validation
        uses: ai-cfia/github-workflows/.github/workflows/workflow-repo-standards-validation.yml@main
        secrets: inherit
      yaml-check:
        name: workflow-yaml-check
        uses: ai-cfia/github-workflows/.github/workflows/workflow-yaml-check.yml@main
        secrets: inherit
